version: 2.1

orbs:
  python: circleci/python:3.6

jobs:
  build-and-test:
    executor: python/default
    environment:
      CIRCLECI_PYTHON_EXECUTOR: python3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
