version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.9
    environment: PYTHONPATH=./src
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install Test requirements
      - run:
          command: pip install -e .[all]
          name: Install Pacakge
      - run:
          command: pytest
          name: Test
          
workflows:
  main:
    jobs:
      - build-and-test
