version: 2.1

orbs:
  python: circleci/python@1.3.0

jobs:
  build-and-test:
    executor: python/default
    environment:
      CIRCLECI_PYTHON_EXECUTOR: python3
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install Test requirements
      - run:
          command: pip install -e .[all]
          name: Install Pacakge
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
